### PR TITLE
Improve memory efficiency

### PR DESCRIPTION
**Pull request by adinapoli**
Hey @vincenthz ,

see [this issue](https://github.com/vincenthz/hs-asn1/pull/19) for context.

This PR does mostly 2 things:
- Ships a minimal stack manifest
- Switch to use `decode` rather than `decodeLenient` in the parser, as the former is faster and consumes less memory (I suppose due to the lack of explicit filtering the latter does), but I would like to check in with you if you think this could have unfathomable consequences for end users.

I suspect more improvements can be made (example: moving away from `String` in favour of `Text`), but I guess this is a start.

### CODE REVIEW

**Comment by vincenthz** [comment]
I really have a hard time taking a decision whether or not it's going to have an unforeseen impact. I need to increase the test tooling (across all OSes) to have some reasonable confidence.

as an alternative way, would it make sense to find out why decodeLenient is so different from decode ? and if possible improve it (which would delay the need to find out if replacing PEM decoding is going to fly)

**Comment by adinapoli** [comment]
> I really have a hard time taking a decision whether or not it's going to have an unforeseen impact. I need to increase the test tooling (across all OSes) to have some reasonable confidence.

That's a solid concern, which I do share as well. I do think we need more testing, but the question would be which test could be good ones to have confidence we are not going to break things badly for virtually all the users in the Haskell ecosystem.

> as an alternative way, would it make sense to find out why decodeLenient is so different from decode ?

I did this kind of research (very empirically) and the reason `decodeLenient` is slower is because it needs to filter over some chars. Here is the [source code for it](http://hackage.haskell.org/package/base64-bytestring-1.0.0.1/docs/src/Data-ByteString-Base64-Lazy.html#decodeLenient):

``` haskell
-- | Decode a base64-encoded string.  This function strictly follows
-- the specification in RFC 4648,
-- <http://www.apps.ietf.org/rfc/rfc4648.html>.
decode :: L.ByteString -> Either String L.ByteString
decode b = -- Returning an Either type means that the entire result will
           -- need to be in memory at once anyway, so we may as well
           -- keep it simple and just convert to and from a strict byte
           -- string
           -- TODO: Use L.{fromStrict,toStrict} once we can rely on
           -- a new enough bytestring
           case B64.decode $ S.concat $ L.toChunks b of
           Left err -> Left err
           Right b' -> Right $ L.fromChunks [b']

-- | Decode a base64-encoded string.  This function is lenient in
-- following the specification from RFC 4648,
-- <http://www.apps.ietf.org/rfc/rfc4648.html>, and will not generate
-- parse errors no matter how poor its input.
decodeLenient :: L.ByteString -> L.ByteString
decodeLenient = L.fromChunks . map B64.decodeLenient . reChunkIn 4 . L.toChunks
              . LC.filter goodChar
    where -- We filter out and '=' padding here, but B64.decodeLenient
          -- handles that
          goodChar c = isAlphaNum c || c == '+' || c == '/'
```

I think when Bryan wrote the library he had very clear the tradeoff in terms of speed/memory, as this is written in the [mirror mercurial repository](https://bitbucket.org/bos/base64-bytestring):

```
This library is written in pure Haskell, and it's fast:
250 MB/sec encoding

200 MB/sec strict decoding (per RFC 4648)

100 MB/sec lenient decoding
```

This is as far as my detective abilities can go! But I'm definitely up for some brainstorming on how we could improve things, whether is as part of this library or the `base64-bytestring` one.

I hope I'm saying meaningful things, still no ☕  in this brain this morning 😂

**Comment by vincenthz** [comment]
This is now using base64 from `memory`, without any leniency. we can now close this, finally \o/

**Comment by adinapoli** [comment]
Haha, at last :P

**Pull request closed without merging**
